### ISSUE TITLE
Add `Location` info when returning `Created` HTTP status

### ISSUE THREAD

**Issue by thiagolunardi** [fel1xw/reply#1]
Following the below statement from [here](https://geemus.gitbooks.io/http-api-design/content/en/responses/return-appropriate-status-codes.html):

> 201: Request succeeded for a POST, or PUT call that synchronously created a new resource. It is also best practice to provide a 'Location' header pointing to the newly created resource. This is particularly useful in the POST context as the new resource will have a different URL than the original request

Add parameter to `Create()` function to expect the Location information.

**Comment by fel1xw** [comment]
@thiagolunardi Sounds good, 

I will a a new function like following which sets the `Location` header.

```go
func CreatedWithLocation(w http.ResponseWriter, location string, data interface{}) {}
```

**Comment by fel1xw** [comment]
I decided to not implement that one as it would quite pollute the exposed function set, I need to think about another solution how to tackle that. :)
